---

- name: update instance
  shell: sudo yum update -y
  become: yes
  become_user: root

- name: install epel repository
  shell: amazon-linux-extras install epel -y
  become: yes
  become_user: root

- name: Uninstall Apache
  tags: uninstall_apache
  yum:
    name: httpd
    autoremove: yes
    state: absent

- name: Install nginx
  yum: name=nginx state=latest update_cache=yes
  become: yes
  become_user: root

- name: Enable nginx
  shell: systemctl enable nginx
  become: yes
  become_user: root

- name: Start nginx
  shell: systemctl start nginx
  become: yes
  become_user: root

- name: Copy proxy config file to node
  ansible.builtin.copy:
    src: ~/inventory/api/files/vodafoneapi.conf
    dest: "{{proxy_dir}}"
    owner: root
    group: root
    mode: '0644'
    follow: yes

- name: Copy nginx config file to node
  copy:
    src: ~/inventory/api/files/nginx.conf
    dest: "{{conf_dir}}"
    owner: root
    group: root
    mode: '0644'
    follow: yes

- name: Start nginx
  shell: systemctl restart nginx

- name: Install Packages
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
    - "@Development tools"
    - git
    - curl

- name: install node.js
  shell: yum install nodejs -y

- name: Create APP Directory
  file: path={{rootDir}}/{{appDir}} state=directory

- name: Git Clone Repo
  git: repo=https://github.com/{{account}}/{{repo}}.git dest={{rootDir}}/{{appDir}} update=yes force=yes 
  register: git_finished

- name: Running NPM install
  npm: path={{rootDir}}/{{appDir}}
  register: npm_finished
  when: git_finished.changed

- name: Install forever to run app
  npm: name=forever global=yes state=present

- name: Check list of apps running
  command: forever list
  register: forever_list
  changed_when: false

- name: Start  app
  command: forever start "{{rootDir}}/{{appDir}}/server.js"
  when: "forever_list.stdout.find('{{rootDir}}/{{appDir}}/server.js') == -1"
